FROM mambaorg/micromamba:latest

USER root

RUN apt-get update && apt-get install -y git nano curl wget build-essential && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN micromamba create -n colbert python=3.11 cuda -c nvidia/label/11.7.1 -c conda-forge

RUN micromamba install -n colbert faiss-gpu -c pytorch -c conda-forge

ENV CONDA_DEFAULT_ENV=colbert
ENV PATH=/opt/conda/envs/colbert/bin:$PATH

RUN micromamba run -n colbert pip install colbert-ai[torch]==0.2.21
RUN micromamba run -n colbert pip install transformers==4.38.2
RUN micromamba run -n colbert pip install pytrec_eval

RUN pwd

RUN echo "eval \"\$(micromamba shell hook --shell bash)\"" >> ~/.bashrc && \
    echo "micromamba activate colbert" >> ~/.bashrc

CMD ["/bin/bash"]