FROM mambaorg/micromamba:latest

USER root

RUN apt-get update && apt-get install -y git nano curl wget build-essential && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN micromamba create -n colbert python=3.11 cuda -c nvidia/label/11.7.1 -c conda-forge

RUN micromamba install -n colbert faiss-gpu -c pytorch -c conda-forge

ENV CONDA_DEFAULT_ENV=colbert
ENV PATH=/opt/conda/envs/colbert/bin:$PATH

RUN micromamba run -n colbert pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ colbert-ai==0.2.22
RUN micromamba run -n colbert pip install torch==2.8.0
RUN micromamba run -n colbert pip install transformers
RUN micromamba run -n colbert pip install pytrec_eval
RUN micromamba run -n colbert pip install pandas

RUN pwd

RUN echo "eval \"\$(micromamba shell hook --shell bash)\"" >> ~/.bashrc && \
    echo "micromamba activate colbert" >> ~/.bashrc

CMD ["/bin/bash"]